CELL_SIZE: int = 200
CELL_CENTER_OFFSET: int = 50
CELL_SHAPE_OFFSET: int = 75

EMPTY_CELL = '-'
PLAYER_1 = 'x'
PLAYER_2 = 'o'

EMPTY_GRID = [
    [EMPTY_CELL, EMPTY_CELL, EMPTY_CELL],
    [EMPTY_CELL, EMPTY_CELL, EMPTY_CELL],
    [EMPTY_CELL, EMPTY_CELL, EMPTY_CELL]
]
